import operator
from typing import Annotated, TypedDict

"""
AgentState: Defines the shared state structure for the LangGraph agent.

This state is passed between all nodes (planner, researcher, responder) 
and persisted across conversation turns using SQLite checkpointing.
"""


class AgentState(TypedDict, total=False):
    topic: str  # The current research topic/query from the user
    plan: list[str]  # List of search queries generated by the planner node
    findings: list[str]  # Research results collected by the researcher node (reset each turn)
    messages: Annotated[list[str], operator.add]  # Conversation history
    current_step: int  # Tracks which step of the plan is currently being executed
    max_steps: int  # Upper bound for each new plan
    errors: list[str]  # Failures are not included in the research evidence
    answer: str  # Final Markdown report
    demo: bool  # Persist the session mode so resume cannot mix adapters
